spring:
    profiles:
        active: local
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: validate
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            use-new-id-generator-mappings: false
        properties:
            hibernate:
                format_sql: true
                default_batch_fetch_size: 256
                batch_fetch_style: dynamic
                query.in_clause_parameter_padding: true
                jdbc:
                    time_zone: UTC
                    batch_size: 1000
        database-platform: org.hibernate.dialect.MySQL8Dialect
    liquibase:
        change-log: classpath:db/changelog/db.changelog-master.xml
        enabled: true

server:
    port: 8199
    address: 0.0.0.0
    servlet:
        encoding:
            charset: UTF-8
            force: true
---
spring:
    config:
        activate:
            on-profile: local
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3312/liquibase_local?serverTimezone=UTC&characterEncoding=UTF-8
        username: liquibase_starter
        password: liquibase_starter
